version: '3.8'

services:
  remitone-app:
    build:
      context: .
      dockerfile: Dockerfile
    image: remitone-app
    container_name: remitone-container
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=production
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped
