version: '3.8'

services:
  remitone:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      DB_USER: mysql
      DB_PASSWORD: rjBqQ0NgPXsNlkFq1ue2o2jxNTkZPjeFDhhJmXBu9ePFMLT5Z7KfqCSQiJJZFu9b
      DB_HOST: qow8wkc8o4o4cgw4w00gccco
      DB_PORT: 3306
      DB_NAME: default
