package com.codedsolutions47.remitonewrapper.dtos.request;

import lombok.Data;

@Data
public class CreateBeneficiaryRequest {
    private String name;
    private String fname;
    private String mname;
    private String lname;
    private String organisation_type;
    private String company_name;
    private String company_type;
    private String company_reg_no;
    private String address1;
    private String address2;
    private String address3;
    private String city;
    private String state;
    private String postcode;
    private String country;
    private String nationality;
    private String dob;
    private String fathers_name;
    private String mothers_name;
    private String national_id_number;
    private String gender;
    private String telephone;
    private String mobile;
    private String email;
    private String id_type;
    private String id_details;
    private String id_start;
    private String id_expiry;
    private String id_issued_by;
    private String id_issue_place;
    private String id_issue_country;
    private String id_scan;
    private String id2_type;
    private String id2_details;
    private String id2_expiry;
    private String id2_issue_place;
    private String benef_employer_id_details;
    private String benef_taxpayer_reg;
    private String benef_occupation;
    private String card_type;
    private String card_number;
    private String account_number;
    private String bank;
    private String bank_branch;
    private String bank_branch_city;
    private String bank_branch_state;
    private String bank_branch_telephone;
    private String bank_branch_manager;
    private String benef_bank_swift_code;
    private String benef_bank_ifsc_code;
    private String benef_bank_iban_code;
    private String benef_bank_account_name;
    private String benef_ac_type;
    private String homedelivery_notes;
    private String enabled;
    private String suspicious;
    private String suspicion_reason;
    private int linked_member_id;
}
